import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../core/theme/app_colors.dart';
import '../../core/repositories/ghost_repository.dart';
import '../../core/repositories/auth_repository.dart';
import '../../core/models/ghost_post.dart';

class PostGhostScreen extends ConsumerStatefulWidget {
  const PostGhostScreen({super.key});

  @override
  ConsumerState<PostGhostScreen> createState() => _PostGhostScreenState();
}

class _PostGhostScreenState extends ConsumerState<PostGhostScreen> {
  final _textController = TextEditingController();
  String? _selectedMood;
  int _charCount = 0;
  final int _maxChars = 500;
  bool _isLoading = false;

  final List<Map<String, dynamic>> _moods = [
    {
      'label': 'Stressed',
      'icon': Icons.sentiment_very_dissatisfied_rounded,
      'color': const Color(0xFFDC2626),
    },
    {
      'label': 'Happy',
      'icon': Icons.sentiment_very_satisfied_rounded,
      'color': const Color(0xFF059669),
    },
    {
      'label': 'Confused',
      'icon': Icons.psychology_rounded,
      'color': const Color(0xFFD97706),
    },
    {
      'label': 'Venting',
      'icon': Icons.whatshot_rounded,
      'color': const Color(0xFF7E22CE),
    },
    {
      'label': 'Motivated',
      'icon': Icons.rocket_launch_rounded,
      'color': const Color(0xFF2563EB),
    },
  ];

  Future<void> _submit() async {
    if (_textController.text.trim().isEmpty || _selectedMood == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select a mood and write something!')));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final user = Supabase.instance.client.auth.currentUser!;
      final alias = AuthRepository().currentGhostAlias;
      
      final post = GhostPost(
        id: '', // Will be generated by DB
        text: _textController.text.trim(),
        mood: _selectedMood!,
        createdAt: DateTime.now(),
        authorId: user.id,
        authorAlias: alias,
      );

      await GhostRepository().createPost(post);
      
      if (mounted) Navigator.pop(context);
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF1A0533),
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_rounded, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'New Ghost Post',
          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
        ),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Anonymous badge
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.1),
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: Colors.white.withOpacity(0.1)),
              ),
              child: const Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(Icons.visibility_off_rounded, color: Colors.white70, size: 18),
                  SizedBox(width: 8),
                  Text(
                    'This post is completely anonymous',
                    style: TextStyle(color: Colors.white70, fontSize: 13, fontWeight: FontWeight.w600),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 28),

            const Text(
              'How are you feeling?',
              style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 16),
            Wrap(
              spacing: 10,
              runSpacing: 10,
              children: _moods.map((mood) {
                final isSelected = _selectedMood == mood['label'];
                return GestureDetector(
                  onTap: () => setState(() => _selectedMood = mood['label'] as String),
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                    decoration: BoxDecoration(
                      color: isSelected ? (mood['color'] as Color) : Colors.white.withOpacity(0.08),
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(color: isSelected ? Colors.transparent : Colors.white.withOpacity(0.15)),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(mood['icon'] as IconData, color: isSelected ? Colors.white : Colors.white60, size: 18),
                        const SizedBox(width: 8),
                        Text(
                          mood['label'] as String,
                          style: TextStyle(color: isSelected ? Colors.white : Colors.white60, fontWeight: FontWeight.bold, fontSize: 13),
                        ),
                      ],
                    ),
                  ),
                );
              }).toList(),
            ),
            const SizedBox(height: 28),

            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text('What\'s on your mind?', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
                Text('${_charCount}/$_maxChars', 
                  style: TextStyle(color: _charCount > _maxChars ? AppColors.error : Colors.white54, fontSize: 12)),
              ],
            ),
            const SizedBox(height: 16),
            Container(
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.08),
                borderRadius: BorderRadius.circular(20),
                border: Border.all(color: Colors.white.withOpacity(0.1)),
              ),
              child: TextField(
                controller: _textController,
                maxLines: 6,
                onChanged: (val) => setState(() => _charCount = val.length),
                style: const TextStyle(color: Colors.white, fontSize: 16, height: 1.6),
                decoration: InputDecoration(
                  hintText: 'Share your thoughts, feelings, or just vent...',
                  hintStyle: TextStyle(color: Colors.white.withOpacity(0.3)),
                  border: InputBorder.none,
                  contentPadding: const EdgeInsets.all(20),
                ),
              ),
            ),
            const SizedBox(height: 48),

            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _isLoading ? null : _submit,
                icon: _isLoading 
                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                  : const Icon(Icons.visibility_off_rounded, size: 20),
                label: Text(
                  _isLoading ? 'Whispering...' : 'Post Anonymously',
                  style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                ),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF7E22CE),
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 18),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                ),
              ),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }
}
